# SGD Regressor Example Notebook

In [1]:
# importing my linear regression model and sklearn's linear regression
%cd ..
from algorithms.linear_model.SGDRegressor import SGDRegressor
import numpy as np

e:\KTorch


C:\Users\Karim\AppData\Roaming\Python\Python311\site-packages\IPython\core\magics\osm.py:417: UserWarning: using dhist requires you to install the `pickleshare` library.
  self.shell.db['dhist'] = compress_dhist(dhist)[-100:]


In [2]:
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split
import numpy as np

# Set a random seed for reproducibility
np.random.seed(1000)

# Create a toy dataset for linear regression
X, y = make_regression(n_samples=1000, n_features=1, noise=0.4)

# Split the dataset into a training and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

X_train.shape , y_train.shape, X_test.shape, y_test.shape

((800, 1), (800,), (200, 1), (200,))

In [3]:
# Creating the linear regression models
my_model = SGDRegressor(max_iter=1, lr=0.1, loss='squared_loss')

In [4]:
my_model.fit(X_train, y_train)

SGD Regressor model fitted successfully


In [5]:
# Getting the predictions
my_preds = my_model.predict(X_test)
my_preds[:5], y_test[:5]

(array([[-26.0291044 ],
        [  0.89493404],
        [ 54.33845623],
        [119.50399355],
        [-82.95765006]]),
 array([-25.90336373,   0.66142785,  53.91007976, 119.69460986,
        -82.00998113]))

In [6]:
# Fitting my models
my_model.max_iter = 100
my_model.fit(X_train, y_train)

SGD Regressor model fitted successfully


In [7]:
X_test.shape, my_model.coef_.shape, my_model.intercept_.shape

((200, 1), (1, 1), (1, 1))

In [8]:
# Getting the predictions
my_preds = my_model.predict(X_test)
my_preds[:5], y_test[:5]

(array([[-26.0291044 ],
        [  0.89493404],
        [ 54.33845623],
        [119.50399355],
        [-82.95765006]]),
 array([-25.90336373,   0.66142785,  53.91007976, 119.69460986,
        -82.00998113]))

The first 5 nearly predictions are equal