# Loss Functions

In [1]:
%cd ../..

e:\KTorch


C:\Users\Karim\AppData\Roaming\Python\Python311\site-packages\IPython\core\magics\osm.py:417: UserWarning: using dhist requires you to install the `pickleshare` library.
  self.shell.db['dhist'] = compress_dhist(dhist)[-100:]


In [2]:
# imports
import torch

torch.empty(3, dtype=torch.float64).random_(5)

tensor([0., 1., 4.], dtype=torch.float64)

In [3]:
import numpy as np

x = np.array([[1, 2], [3, 4]])
np.diag(x)

array([1, 4])

In [4]:
np.eye(2) * x.reshape(-1, 2, 1)

array([[[1., 0.],
        [0., 2.]],

       [[3., 0.],
        [0., 4.]]])

In [5]:
np.eye(2).shape

(2, 2)

In [6]:
x[:, :, np.newaxis].shape, x[:, np.newaxis, :].shape

((2, 2, 1), (2, 1, 2))

In [7]:
x[: , :, np.newaxis] * x[:, np.newaxis, :]

array([[[ 1,  2],
        [ 2,  4]],

       [[ 9, 12],
        [12, 16]]])

In [8]:
x.reshape(-1, 2, 1) * x.reshape(-1, 1, 2)

array([[[ 1,  2],
        [ 2,  4]],

       [[ 9, 12],
        [12, 16]]])