# Linear Regression Example Notebook

In [1]:
# importing my linear regression model and sklearn's linear regression
%cd ..
from algorithms.linear_model.RidgeRegression import RidgeRegression
from sklearn.linear_model import Ridge
import numpy as np

C:\Users\Karim\AppData\Roaming\Python\Python311\site-packages\IPython\core\magics\osm.py:417: UserWarning: using dhist requires you to install the `pickleshare` library.
  self.shell.db['dhist'] = compress_dhist(dhist)[-100:]


f:\KTorch


In [2]:
# Getting the dataset
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [3]:
# Getting our data
X, y = fetch_california_housing(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
len(X_train), len(X_test), len(y_train), len(y_test)

(16512, 4128, 16512, 4128)

In [4]:
# Scale features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
X_train[0], X_test[0]

(array([-0.326196  ,  0.34849025, -0.17491646, -0.20836543,  0.76827628,
         0.05137609, -1.3728112 ,  1.27258656]),
 array([-1.15508475, -0.28632369, -0.52068576, -0.17174603, -0.03030109,
         0.06740798,  0.1951    ,  0.28534728]))

In [5]:
# Creating the linear regression models
my_model = RidgeRegression()
sklearn_model = Ridge()

In [6]:
# Fitting the models
my_model.fit(X_train, y_train)
sklearn_model.fit(X_train, y_train)

Ridge Regression model fitted successfully


Ridge()

In [7]:
# Getting the predictions
my_preds = my_model.predict(X_test)
sklearn_preds = sklearn_model.predict(X_test)
my_preds[:5], sklearn_preds[:5]

(array([0.71934676, 1.76372118, 2.70918353, 2.83863131, 2.60405189]),
 array([0.71947224, 1.76384666, 2.709309  , 2.83875678, 2.60417736]))

The first 5 predictions are quite similar

In [8]:
# Comparing the results
np.testing.assert_array_almost_equal(my_preds, sklearn_preds, decimal=3)
print("Results are the same!")

Results are the same!


In [9]:
from sklearn.metrics import mean_squared_error
my_mse = mean_squared_error(y_test, my_preds)
sklearn_mse = mean_squared_error(y_test, sklearn_preds)
print(f"My model's MSE: {my_mse}")
print(f"Sklearn's model's MSE: {sklearn_mse}")
np.testing.assert_approx_equal(my_mse, sklearn_mse, significant=5)
print("MSEs are the same!")

My model's MSE: 0.555855746832112
Sklearn's model's MSE: 0.5558548589435969
MSEs are the same!


In [10]:
# Testing the coefficient of determination
sklearn_score = sklearn_model.score(X_test, y_test)
my_score = my_model.score(X_test, y_test)
print(f"My model's coefficient of determination: {my_score}")
print(f"Sklearn's model's coefficient of determination: {sklearn_score}")
np.testing.assert_approx_equal(my_score, sklearn_score, significant=2)
print("The coefficient of determination are the same!")

My model's coefficient of determination: 0.58
Sklearn's model's coefficient of determination: 0.5758157428913686
The coefficient of determination are the same!
